---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - review_requested
      - reopened
      - synchronize
      - auto_merge_enabled
    branches:
      - main
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
      - name: Install dependencies
        run: npm install
      - name: Commitlint
        if: github.event_name == 'push'
        run: npm run commitlint
      - name: PR Commitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        if: github.event_name == 'pull_request'
        run: npx commitlint -- $TITLE
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
